services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AXE
      - MONGO_INITDB_ROOT_PASSWORD=AXE
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=AXE
      - ME_CONFIG_MONGODB_ADMINPASSWORD=AXE
      - ME_CONFIG_MONGODB_SERVER=mongodb
    volumes:
      - mongodb-data:/data
    depends_on:
      - mongodb


volumes:
  mongodb-data: {}



